name: Publish package to GitHub Packages
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish package
        run: ./gradlew publish
        env:
          USERNAME: ${{ secrets GRADLE_PACKAGES_USERNAME }}
          TOKEN: ${{ secrets.GRADLE_PACKAGES_TOKEN }}
